{% set name = "uuid-utils" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uuid_utils-{{ version }}.tar.gz
  sha256: 5db0e1890e8f008657ffe6ded4d9459af724ab114cfe82af1557c87545301539

build:
  number: 1
  python_version_independent: true   # [is_abi3]
  skip: True                         # [is_abi3 and not is_python_min]
  ignore_run_exports:
   - cross-python_{{ target_platform }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - python-abi3                            # [is_abi3]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin                                # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin
    - pip
  run:
    - python


test:
  imports:
    - uuid_utils
  commands:
    - pip check
    - abi3audit $SP_DIR/uuid_utils/_uuid_utils.abi3.so -s -v --assume-minimum-abi3 {{ python_min }}   # [unix]
    - abi3audit %SP_DIR%/uuid_utils/_uuid_utils.dll -s -v --assume-minimum-abi3 {{ python_min }}       # [win]
  requires:
    - pip
    - abi3audit

about:
  home: https://github.com/aminalaee/uuid-utils
  summary: Drop-in replacement for Python UUID in Rust
  dev_url: https://github.com/aminalaee/uuid-utils
  license: BSD-3-Clause
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
