{% set name = "uuid-utils" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uuid_utils-{{ version }}.tar.gz
  sha256: 18cf2b7083da7f3cca0517647213129eb16d20d7ed0dd74b3f4f8bff2aa334ea

build:
  number: 0
  python_version_independent: true  # [is_abi3]
  skip: true  # [is_abi3 and not is_python_min]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin                                # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - python-abi3                            # [is_abi3]
    - maturin
    - pip
  run:
    - python


test:
  imports:
    - uuid_utils
  commands:
    - pip check
    - abi3audit $SP_DIR/uuid_utils/_uuid_utils.abi3.so -s -v --assume-minimum-abi3 {{ python_min }}   # [unix and build_platform == target_platform]
    - abi3audit %SP_DIR%/uuid_utils/_uuid_utils.pyd -s -v --assume-minimum-abi3 {{ python_min }}       # [win]
  requires:
    - pip
    - abi3audit  # [build_platform == target_platform]

about:
  home: https://github.com/aminalaee/uuid-utils
  summary: Drop-in replacement for Python UUID in Rust
  dev_url: https://github.com/aminalaee/uuid-utils
  license: BSD-3-Clause
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
